### ISSUE TITLE
Cannot Reconstruct

### ISSUE THREAD

**Issue by chendind** [KKodiac/ObjectCaptureApp-WWDC23#1]
When I click "Finish Captures", and then click "Reconstruct", the app screen is static and cannot be moved. I'm not a professional developer, has anyone encountered the same problem and how to solve it?

**Comment by KKodiac** [comment]
Thanks for pointing out the PhotogrammetrySession not working. I'm aware of the issue and will be working to fix it😊

**Comment by KKodiac** [comment]
Hello, I have added new changes and fixes to the app and the issue you have opened is hopefully fixed. Please checkout the new changes.

**Comment by chendind** [comment]
thank you, let me have a try
